title: DNB Hackathon
nav_title: DNB Hack<span class="hide-very-narrow">athon</span><br><small><span class="hide-very-narrow">with </span>Digital Nasional Berhad</small>

event_date: 15 Feb - 30 March 2023
registration_opens_date: 15 Feb 2023
registration_closes_date: 22 Feb 2023
submission_date: 23 Feb - 16 March 2023
team_semifinal_announcement: 23 March 2023
pitch_presentation: 29 March - 30 March 2023
result_date: 30 March 2023

author: Digital Nasional Berhad
mailbox_address: mani.kagita@digital-nasional.com.my

description:
  The Digital Hackathon is a 15-day hackathon event, organised by the the Digital Nasional Berhad. Over the course of the event, teams of
  Malaysia University Students will...

url: "https://manikumarkagita.github.io/hackathon/"
github_repo: hackathon

theme: minima


# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - index.md
  - registration.md
  - projects.md
  - faq.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: demo

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: demo

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
